version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d  # Ensure this line is included
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      DATABASE_NAME: ecommerce
      FLASK_ENV: development
      FLASK_DEBUG: 1
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    networks:
      - app-network

  product-service:
    build: ./product-service
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      DATABASE_NAME: ecommerce
      FLASK_ENV: development
      FLASK_DEBUG: 1
    depends_on:
      - postgres
    ports:
      - '5001:5001'
    networks:
      - app-network

  order-service:
    build: ./order-service
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      DATABASE_NAME: ecommerce
      FLASK_ENV: development
      FLASK_DEBUG: 1
    depends_on:
      - postgres
    ports:
      - '5002:5002'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
